package sz.iecas.model;

public class EducationExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.Edu_id
     *
     * @mbggenerated
     */
    private Integer eduId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.Resume_id
     *
     * @mbggenerated
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.School
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.Province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.Degree
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.Major
     *
     * @mbggenerated
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.Rank
     *
     * @mbggenerated
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.GraduateDate
     *
     * @mbggenerated
     */
    private String graduatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.StartDate
     *
     * @mbggenerated
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column education_extend.City_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.Edu_id
     *
     * @return the value of education_extend.Edu_id
     *
     * @mbggenerated
     */
    public Integer getEduId() {
        return eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.Edu_id
     *
     * @param eduId the value for education_extend.Edu_id
     *
     * @mbggenerated
     */
    public void setEduId(Integer eduId) {
        this.eduId = eduId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.Resume_id
     *
     * @return the value of education_extend.Resume_id
     *
     * @mbggenerated
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.Resume_id
     *
     * @param resumeId the value for education_extend.Resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.School
     *
     * @return the value of education_extend.School
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.School
     *
     * @param school the value for education_extend.School
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.Province_id
     *
     * @return the value of education_extend.Province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.Province_id
     *
     * @param provinceId the value for education_extend.Province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.Degree
     *
     * @return the value of education_extend.Degree
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.Degree
     *
     * @param degree the value for education_extend.Degree
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.Major
     *
     * @return the value of education_extend.Major
     *
     * @mbggenerated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.Major
     *
     * @param major the value for education_extend.Major
     *
     * @mbggenerated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.Rank
     *
     * @return the value of education_extend.Rank
     *
     * @mbggenerated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.Rank
     *
     * @param rank the value for education_extend.Rank
     *
     * @mbggenerated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.GraduateDate
     *
     * @return the value of education_extend.GraduateDate
     *
     * @mbggenerated
     */
    public String getGraduatedate() {
        return graduatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.GraduateDate
     *
     * @param graduatedate the value for education_extend.GraduateDate
     *
     * @mbggenerated
     */
    public void setGraduatedate(String graduatedate) {
        this.graduatedate = graduatedate == null ? null : graduatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.StartDate
     *
     * @return the value of education_extend.StartDate
     *
     * @mbggenerated
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.StartDate
     *
     * @param startdate the value for education_extend.StartDate
     *
     * @mbggenerated
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column education_extend.City_id
     *
     * @return the value of education_extend.City_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column education_extend.City_id
     *
     * @param cityId the value for education_extend.City_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}