package sz.iecas.model;

public class ExperienceExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience_extend.Experience_id
     *
     * @mbggenerated
     */
    private Integer experienceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience_extend.Resume_id
     *
     * @mbggenerated
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience_extend.Experience_Description
     *
     * @mbggenerated
     */
    private String experienceDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience_extend.Experience_id
     *
     * @return the value of experience_extend.Experience_id
     *
     * @mbggenerated
     */
    public Integer getExperienceId() {
        return experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience_extend.Experience_id
     *
     * @param experienceId the value for experience_extend.Experience_id
     *
     * @mbggenerated
     */
    public void setExperienceId(Integer experienceId) {
        this.experienceId = experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience_extend.Resume_id
     *
     * @return the value of experience_extend.Resume_id
     *
     * @mbggenerated
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience_extend.Resume_id
     *
     * @param resumeId the value for experience_extend.Resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience_extend.Experience_Description
     *
     * @return the value of experience_extend.Experience_Description
     *
     * @mbggenerated
     */
    public String getExperienceDescription() {
        return experienceDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience_extend.Experience_Description
     *
     * @param experienceDescription the value for experience_extend.Experience_Description
     *
     * @mbggenerated
     */
    public void setExperienceDescription(String experienceDescription) {
        this.experienceDescription = experienceDescription == null ? null : experienceDescription.trim();
    }
}