package sz.iecas.model;

import java.util.Date;

public class InterviewTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Interview_id
     *
     * @mbggenerated
     */
    private Integer interviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Resume_id
     *
     * @mbggenerated
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Employer
     *
     * @mbggenerated
     */
    private String employer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Interview_type
     *
     * @mbggenerated
     */
    private Integer interviewType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview_table.Interview_time
     *
     * @mbggenerated
     */
    private Date interviewTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Interview_id
     *
     * @return the value of interview_table.Interview_id
     *
     * @mbggenerated
     */
    public Integer getInterviewId() {
        return interviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Interview_id
     *
     * @param interviewId the value for interview_table.Interview_id
     *
     * @mbggenerated
     */
    public void setInterviewId(Integer interviewId) {
        this.interviewId = interviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Resume_id
     *
     * @return the value of interview_table.Resume_id
     *
     * @mbggenerated
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Resume_id
     *
     * @param resumeId the value for interview_table.Resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Status
     *
     * @return the value of interview_table.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Status
     *
     * @param status the value for interview_table.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Comment
     *
     * @return the value of interview_table.Comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Comment
     *
     * @param comment the value for interview_table.Comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Employer
     *
     * @return the value of interview_table.Employer
     *
     * @mbggenerated
     */
    public String getEmployer() {
        return employer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Employer
     *
     * @param employer the value for interview_table.Employer
     *
     * @mbggenerated
     */
    public void setEmployer(String employer) {
        this.employer = employer == null ? null : employer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Interview_type
     *
     * @return the value of interview_table.Interview_type
     *
     * @mbggenerated
     */
    public Integer getInterviewType() {
        return interviewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Interview_type
     *
     * @param interviewType the value for interview_table.Interview_type
     *
     * @mbggenerated
     */
    public void setInterviewType(Integer interviewType) {
        this.interviewType = interviewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview_table.Interview_time
     *
     * @return the value of interview_table.Interview_time
     *
     * @mbggenerated
     */
    public Date getInterviewTime() {
        return interviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview_table.Interview_time
     *
     * @param interviewTime the value for interview_table.Interview_time
     *
     * @mbggenerated
     */
    public void setInterviewTime(Date interviewTime) {
        this.interviewTime = interviewTime;
    }
}