package sz.iecas.model;

public class JobInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.maxSalary
     *
     * @mbggenerated
     */
    private Integer maxsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.minSalary
     *
     * @mbggenerated
     */
    private Integer minsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.publishTime
     *
     * @mbggenerated
     */
    private String publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.endTime
     *
     * @mbggenerated
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.departmentId
     *
     * @mbggenerated
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.degree
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_status
     *
     * @mbggenerated
     */
    private Integer jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.major_name
     *
     * @mbggenerated
     */
    private String majorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.id
     *
     * @return the value of job_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.id
     *
     * @param id the value for job_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.name
     *
     * @return the value of job_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.name
     *
     * @param name the value for job_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.type
     *
     * @return the value of job_info.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.type
     *
     * @param type the value for job_info.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.maxSalary
     *
     * @return the value of job_info.maxSalary
     *
     * @mbggenerated
     */
    public Integer getMaxsalary() {
        return maxsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.maxSalary
     *
     * @param maxsalary the value for job_info.maxSalary
     *
     * @mbggenerated
     */
    public void setMaxsalary(Integer maxsalary) {
        this.maxsalary = maxsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.minSalary
     *
     * @return the value of job_info.minSalary
     *
     * @mbggenerated
     */
    public Integer getMinsalary() {
        return minsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.minSalary
     *
     * @param minsalary the value for job_info.minSalary
     *
     * @mbggenerated
     */
    public void setMinsalary(Integer minsalary) {
        this.minsalary = minsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.publishTime
     *
     * @return the value of job_info.publishTime
     *
     * @mbggenerated
     */
    public String getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.publishTime
     *
     * @param publishtime the value for job_info.publishTime
     *
     * @mbggenerated
     */
    public void setPublishtime(String publishtime) {
        this.publishtime = publishtime == null ? null : publishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.endTime
     *
     * @return the value of job_info.endTime
     *
     * @mbggenerated
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.endTime
     *
     * @param endtime the value for job_info.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.num
     *
     * @return the value of job_info.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.num
     *
     * @param num the value for job_info.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.departmentId
     *
     * @return the value of job_info.departmentId
     *
     * @mbggenerated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.departmentId
     *
     * @param departmentid the value for job_info.departmentId
     *
     * @mbggenerated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.address
     *
     * @return the value of job_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.address
     *
     * @param address the value for job_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.degree
     *
     * @return the value of job_info.degree
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.degree
     *
     * @param degree the value for job_info.degree
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_status
     *
     * @return the value of job_info.job_status
     *
     * @mbggenerated
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_status
     *
     * @param jobStatus the value for job_info.job_status
     *
     * @mbggenerated
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.major_name
     *
     * @return the value of job_info.major_name
     *
     * @mbggenerated
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.major_name
     *
     * @param majorName the value for job_info.major_name
     *
     * @mbggenerated
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }
}