package sz.iecas.model;

public class JobInfoWithBLOBs extends JobInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_desc
     *
     * @mbggenerated
     */
    private String jobDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_require
     *
     * @mbggenerated
     */
    private String jobRequire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_desc
     *
     * @return the value of job_info.job_desc
     *
     * @mbggenerated
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_desc
     *
     * @param jobDesc the value for job_info.job_desc
     *
     * @mbggenerated
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc == null ? null : jobDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_require
     *
     * @return the value of job_info.job_require
     *
     * @mbggenerated
     */
    public String getJobRequire() {
        return jobRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_require
     *
     * @param jobRequire the value for job_info.job_require
     *
     * @mbggenerated
     */
    public void setJobRequire(String jobRequire) {
        this.jobRequire = jobRequire == null ? null : jobRequire.trim();
    }
}