package sz.iecas.model;

public class LanguageExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language_extend.Language_id
     *
     * @mbggenerated
     */
    private Integer languageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language_extend.Resume_id
     *
     * @mbggenerated
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language_extend.Language_type
     *
     * @mbggenerated
     */
    private String languageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column language_extend.Proficiency
     *
     * @mbggenerated
     */
    private Integer proficiency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language_extend.Language_id
     *
     * @return the value of language_extend.Language_id
     *
     * @mbggenerated
     */
    public Integer getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language_extend.Language_id
     *
     * @param languageId the value for language_extend.Language_id
     *
     * @mbggenerated
     */
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language_extend.Resume_id
     *
     * @return the value of language_extend.Resume_id
     *
     * @mbggenerated
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language_extend.Resume_id
     *
     * @param resumeId the value for language_extend.Resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language_extend.Language_type
     *
     * @return the value of language_extend.Language_type
     *
     * @mbggenerated
     */
    public String getLanguageType() {
        return languageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language_extend.Language_type
     *
     * @param languageType the value for language_extend.Language_type
     *
     * @mbggenerated
     */
    public void setLanguageType(String languageType) {
        this.languageType = languageType == null ? null : languageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column language_extend.Proficiency
     *
     * @return the value of language_extend.Proficiency
     *
     * @mbggenerated
     */
    public Integer getProficiency() {
        return proficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column language_extend.Proficiency
     *
     * @param proficiency the value for language_extend.Proficiency
     *
     * @mbggenerated
     */
    public void setProficiency(Integer proficiency) {
        this.proficiency = proficiency;
    }
}