package sz.iecas.model;

public class ProjectExtendWithBLOBs extends ProjectExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_extend.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_extend.Role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_extend.Description
     *
     * @return the value of project_extend.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_extend.Description
     *
     * @param description the value for project_extend.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_extend.Role
     *
     * @return the value of project_extend.Role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_extend.Role
     *
     * @param role the value for project_extend.Role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}