package sz.iecas.model;

import java.util.ArrayList;
import java.util.List;

public class ProjectExtendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public ProjectExtendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectsIdIsNull() {
            addCriterion("Projects_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectsIdIsNotNull() {
            addCriterion("Projects_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectsIdEqualTo(Integer value) {
            addCriterion("Projects_id =", value, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdNotEqualTo(Integer value) {
            addCriterion("Projects_id <>", value, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdGreaterThan(Integer value) {
            addCriterion("Projects_id >", value, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Projects_id >=", value, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdLessThan(Integer value) {
            addCriterion("Projects_id <", value, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdLessThanOrEqualTo(Integer value) {
            addCriterion("Projects_id <=", value, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdIn(List<Integer> values) {
            addCriterion("Projects_id in", values, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdNotIn(List<Integer> values) {
            addCriterion("Projects_id not in", values, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdBetween(Integer value1, Integer value2) {
            addCriterion("Projects_id between", value1, value2, "projectsId");
            return (Criteria) this;
        }

        public Criteria andProjectsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Projects_id not between", value1, value2, "projectsId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNull() {
            addCriterion("Resume_id is null");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNotNull() {
            addCriterion("Resume_id is not null");
            return (Criteria) this;
        }

        public Criteria andResumeIdEqualTo(Integer value) {
            addCriterion("Resume_id =", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotEqualTo(Integer value) {
            addCriterion("Resume_id <>", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThan(Integer value) {
            addCriterion("Resume_id >", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Resume_id >=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThan(Integer value) {
            addCriterion("Resume_id <", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThanOrEqualTo(Integer value) {
            addCriterion("Resume_id <=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIn(List<Integer> values) {
            addCriterion("Resume_id in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotIn(List<Integer> values) {
            addCriterion("Resume_id not in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdBetween(Integer value1, Integer value2) {
            addCriterion("Resume_id between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Resume_id not between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andProjectsNameIsNull() {
            addCriterion("Projects_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectsNameIsNotNull() {
            addCriterion("Projects_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectsNameEqualTo(String value) {
            addCriterion("Projects_name =", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameNotEqualTo(String value) {
            addCriterion("Projects_name <>", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameGreaterThan(String value) {
            addCriterion("Projects_name >", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameGreaterThanOrEqualTo(String value) {
            addCriterion("Projects_name >=", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameLessThan(String value) {
            addCriterion("Projects_name <", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameLessThanOrEqualTo(String value) {
            addCriterion("Projects_name <=", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameLike(String value) {
            addCriterion("Projects_name like", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameNotLike(String value) {
            addCriterion("Projects_name not like", value, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameIn(List<String> values) {
            addCriterion("Projects_name in", values, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameNotIn(List<String> values) {
            addCriterion("Projects_name not in", values, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameBetween(String value1, String value2) {
            addCriterion("Projects_name between", value1, value2, "projectsName");
            return (Criteria) this;
        }

        public Criteria andProjectsNameNotBetween(String value1, String value2) {
            addCriterion("Projects_name not between", value1, value2, "projectsName");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("Time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("Time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("Time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("Time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("Time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("Time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("Time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("Time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("Time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("Time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("Time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("Time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("Time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_extend
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}