package sz.iecas.model;

public class ProjectExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_extend.Projects_id
     *
     * @mbggenerated
     */
    private Integer projectsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_extend.Resume_id
     *
     * @mbggenerated
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_extend.Projects_name
     *
     * @mbggenerated
     */
    private String projectsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_extend.Time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_extend.Projects_id
     *
     * @return the value of project_extend.Projects_id
     *
     * @mbggenerated
     */
    public Integer getProjectsId() {
        return projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_extend.Projects_id
     *
     * @param projectsId the value for project_extend.Projects_id
     *
     * @mbggenerated
     */
    public void setProjectsId(Integer projectsId) {
        this.projectsId = projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_extend.Resume_id
     *
     * @return the value of project_extend.Resume_id
     *
     * @mbggenerated
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_extend.Resume_id
     *
     * @param resumeId the value for project_extend.Resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_extend.Projects_name
     *
     * @return the value of project_extend.Projects_name
     *
     * @mbggenerated
     */
    public String getProjectsName() {
        return projectsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_extend.Projects_name
     *
     * @param projectsName the value for project_extend.Projects_name
     *
     * @mbggenerated
     */
    public void setProjectsName(String projectsName) {
        this.projectsName = projectsName == null ? null : projectsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_extend.Time
     *
     * @return the value of project_extend.Time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_extend.Time
     *
     * @param time the value for project_extend.Time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}