package sz.iecas.model;

public class Zipcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipcode.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipcode.areaid
     *
     * @mbggenerated
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipcode.zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipcode.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipcode.id
     *
     * @return the value of zipcode.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipcode.id
     *
     * @param id the value for zipcode.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipcode.areaid
     *
     * @return the value of zipcode.areaid
     *
     * @mbggenerated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipcode.areaid
     *
     * @param areaid the value for zipcode.areaid
     *
     * @mbggenerated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipcode.zip
     *
     * @return the value of zipcode.zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipcode.zip
     *
     * @param zip the value for zipcode.zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipcode.code
     *
     * @return the value of zipcode.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipcode.code
     *
     * @param code the value for zipcode.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}