package sz.iecas.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sz.iecas.model.DepartmentInfo;
import sz.iecas.model.DepartmentInfoExample;

public interface DepartmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int countByExample(DepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int deleteByExample(DepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int insert(DepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int insertSelective(DepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    List<DepartmentInfo> selectByExample(DepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    DepartmentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DepartmentInfo record, @Param("example") DepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DepartmentInfo record, @Param("example") DepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DepartmentInfo record);
}