package sz.iecas.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sz.iecas.model.ExperienceExtend;
import sz.iecas.model.ExperienceExtendExample;

public interface ExperienceExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int countByExample(ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int deleteByExample(ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer experienceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int insert(ExperienceExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int insertSelective(ExperienceExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    List<ExperienceExtend> selectByExampleWithBLOBs(ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    List<ExperienceExtend> selectByExample(ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    ExperienceExtend selectByPrimaryKey(Integer experienceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExperienceExtend record, @Param("example") ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ExperienceExtend record, @Param("example") ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExperienceExtend record, @Param("example") ExperienceExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExperienceExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ExperienceExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExperienceExtend record);
}