package sz.iecas.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sz.iecas.model.InterviewTable;
import sz.iecas.model.InterviewTableExample;

public interface InterviewTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int countByExample(InterviewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int deleteByExample(InterviewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer interviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int insert(InterviewTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int insertSelective(InterviewTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    List<InterviewTable> selectByExample(InterviewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    InterviewTable selectByPrimaryKey(Integer interviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InterviewTable record, @Param("example") InterviewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InterviewTable record, @Param("example") InterviewTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InterviewTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InterviewTable record);
}