package sz.iecas.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sz.iecas.model.JobInfo;
import sz.iecas.model.JobInfoExample;
import sz.iecas.model.JobInfoWithBLOBs;

public interface JobInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int countByExample(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int deleteByExample(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int insert(JobInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int insertSelective(JobInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    List<JobInfoWithBLOBs> selectByExampleWithBLOBs(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    List<JobInfo> selectByExample(JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    JobInfoWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JobInfoWithBLOBs record, @Param("example") JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") JobInfoWithBLOBs record, @Param("example") JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JobInfo record, @Param("example") JobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(JobInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobInfo record);
}