package sz.iecas.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sz.iecas.model.LanguageExtend;
import sz.iecas.model.LanguageExtendExample;

public interface LanguageExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int countByExample(LanguageExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int deleteByExample(LanguageExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer languageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int insert(LanguageExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int insertSelective(LanguageExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    List<LanguageExtend> selectByExample(LanguageExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    LanguageExtend selectByPrimaryKey(Integer languageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LanguageExtend record, @Param("example") LanguageExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LanguageExtend record, @Param("example") LanguageExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LanguageExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LanguageExtend record);
}