package sz.iecas.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sz.iecas.model.ProjectExtend;
import sz.iecas.model.ProjectExtendExample;
import sz.iecas.model.ProjectExtendWithBLOBs;

public interface ProjectExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int countByExample(ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer projectsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int insert(ProjectExtendWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int insertSelective(ProjectExtendWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    List<ProjectExtendWithBLOBs> selectByExampleWithBLOBs(ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    List<ProjectExtend> selectByExample(ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    ProjectExtendWithBLOBs selectByPrimaryKey(Integer projectsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectExtendWithBLOBs record, @Param("example") ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectExtendWithBLOBs record, @Param("example") ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectExtend record, @Param("example") ProjectExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectExtendWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProjectExtendWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectExtend record);
}